/**
 * Every currency the rate provider quotes — the full fiat list, so any pair a
 * user can name is convertible. Having a currency here does NOT imply we have a
 * price basket for it; that set is much smaller and lives in data/baskets.
 *
 * Rows carry the display metadata the UI needs: the native symbol locals write,
 * the primary issuing country (code, name, flag) and the ISO 4217 minor unit.
 *
 * MINOR-UNIT CAVEAT. `decimals` is the minor unit *as users expect to see it*,
 * which diverges from ISO 4217 in one place: ISO gives IDR two decimals, but the
 * sen has been worthless for decades and rupiah are written whole, so IDR is 0.
 * The three-decimal Gulf and North African dinars (BHD, JOD, KWD, OMR, TND) and
 * the zero-decimal CLP, ISK, JPY, KRW, UGX and VND all match ISO.
 * `decimals` describes *display* precision only — never round with it before a
 * conversion, only after.
 *
 * SHARED CURRENCIES. EUR, XOF, XAF, XCD, XPF and XCG have no single issuing
 * country, so they carry a representative flag plus an `aliases` list naming
 * every member state. Search matches aliases, so "Spain" finds the euro and
 * "Ivory Coast" finds the West African CFA franc. Dollarised and pegged users
 * (Panama → USD, Liechtenstein → CHF) are listed the same way.
 *
 * Pure accounting units are deliberately absent: XDR (IMF Special Drawing
 * Rights) and CLF (Chile's inflation-indexed Unidad de Fomento) are quoted by
 * the provider but are not money anyone spends.
 *
 * Generated against the provider's live list, with hand-curated rows preserved.
 * Sorted by `code`. No external dependencies.
 */

export type Currency = {
  /** ISO 4217 alphabetic code, e.g. "VND". */
  code: string;
  /** English name of the currency, e.g. "Vietnamese Dong". */
  name: string;
  /** Native symbol where one exists, e.g. "₫". Falls back to the code. */
  symbol: string;
  /** Minor-unit digits for display. See the caveat above. */
  decimals: number;
  /** ISO 3166-1 alpha-2 of the primary (or representative) country. */
  countryCode: string;
  /** Human-readable country, or the zone name for a shared currency. */
  country: string;
  /** Flag emoji matching `countryCode`. */
  flag: string;
  /** Set on the most-traded currencies, surfaced first in pickers. */
  popular?: boolean;
  /** Extra country names the search should match. */
  aliases?: readonly string[];
};

const DATA: readonly Currency[] = [
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    decimals: 2,
    countryCode: "AE",
    country: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "AFN",
    decimals: 0,
    countryCode: "AF",
    country: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    symbol: "ALL",
    decimals: 0,
    countryCode: "AL",
    country: "Albania",
    flag: "🇦🇱",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "AMD",
    decimals: 2,
    countryCode: "AM",
    country: "Armenia",
    flag: "🇦🇲",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    symbol: "AOA",
    decimals: 2,
    countryCode: "AO",
    country: "Angola",
    flag: "🇦🇴",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    decimals: 2,
    countryCode: "AR",
    country: "Argentina",
    flag: "🇦🇷",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "$",
    decimals: 2,
    countryCode: "AU",
    country: "Australia",
    flag: "🇦🇺",
    popular: true,
    aliases: ["Kiribati","Nauru","Tuvalu"],
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    symbol: "AWG",
    decimals: 2,
    countryCode: "AW",
    country: "Aruba",
    flag: "🇦🇼",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "AZN",
    decimals: 2,
    countryCode: "AZ",
    country: "Azerbaijan",
    flag: "🇦🇿",
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "BAM",
    decimals: 2,
    countryCode: "BA",
    country: "Bosnia & Herzegovina",
    flag: "🇧🇦",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    symbol: "BBD",
    decimals: 2,
    countryCode: "BB",
    country: "Barbados",
    flag: "🇧🇧",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    decimals: 2,
    countryCode: "BD",
    country: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: "د.ب",
    decimals: 3,
    countryCode: "BH",
    country: "Bahrain",
    flag: "🇧🇭",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "BIF",
    decimals: 0,
    countryCode: "BI",
    country: "Burundi",
    flag: "🇧🇮",
  },
  {
    code: "BMD",
    name: "Bermudan Dollar",
    symbol: "BMD",
    decimals: 2,
    countryCode: "BM",
    country: "Bermuda",
    flag: "🇧🇲",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "BND",
    decimals: 2,
    countryCode: "BN",
    country: "Brunei",
    flag: "🇧🇳",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "BOB",
    decimals: 2,
    countryCode: "BO",
    country: "Bolivia",
    flag: "🇧🇴",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    decimals: 2,
    countryCode: "BR",
    country: "Brazil",
    flag: "🇧🇷",
    popular: true,
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "BSD",
    decimals: 2,
    countryCode: "BS",
    country: "Bahamas",
    flag: "🇧🇸",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "BTN",
    decimals: 2,
    countryCode: "BT",
    country: "Bhutan",
    flag: "🇧🇹",
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    symbol: "BWP",
    decimals: 2,
    countryCode: "BW",
    country: "Botswana",
    flag: "🇧🇼",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "BYN",
    decimals: 2,
    countryCode: "BY",
    country: "Belarus",
    flag: "🇧🇾",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "BZD",
    decimals: 2,
    countryCode: "BZ",
    country: "Belize",
    flag: "🇧🇿",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "$",
    decimals: 2,
    countryCode: "CA",
    country: "Canada",
    flag: "🇨🇦",
    popular: true,
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "CDF",
    decimals: 2,
    countryCode: "CD",
    country: "Congo - Kinshasa",
    flag: "🇨🇩",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    decimals: 2,
    countryCode: "CH",
    country: "Switzerland",
    flag: "🇨🇭",
    popular: true,
    aliases: ["Liechtenstein"],
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "$",
    decimals: 0,
    countryCode: "CL",
    country: "Chile",
    flag: "🇨🇱",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    decimals: 2,
    countryCode: "CN",
    country: "China",
    flag: "🇨🇳",
    popular: true,
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "$",
    decimals: 2,
    countryCode: "CO",
    country: "Colombia",
    flag: "🇨🇴",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "CRC",
    decimals: 2,
    countryCode: "CR",
    country: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: "CUP",
    decimals: 2,
    countryCode: "CU",
    country: "Cuba",
    flag: "🇨🇺",
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    symbol: "CVE",
    decimals: 2,
    countryCode: "CV",
    country: "Cape Verde",
    flag: "🇨🇻",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    decimals: 2,
    countryCode: "CZ",
    country: "Czechia",
    flag: "🇨🇿",
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    symbol: "DJF",
    decimals: 0,
    countryCode: "DJ",
    country: "Djibouti",
    flag: "🇩🇯",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    decimals: 2,
    countryCode: "DK",
    country: "Denmark",
    flag: "🇩🇰",
    aliases: ["Greenland","Faroe Islands"],
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "DOP",
    decimals: 2,
    countryCode: "DO",
    country: "Dominican Republic",
    flag: "🇩🇴",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    symbol: "DZD",
    decimals: 2,
    countryCode: "DZ",
    country: "Algeria",
    flag: "🇩🇿",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "E£",
    decimals: 2,
    countryCode: "EG",
    country: "Egypt",
    flag: "🇪🇬",
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    symbol: "ERN",
    decimals: 2,
    countryCode: "ER",
    country: "Eritrea",
    flag: "🇪🇷",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    decimals: 2,
    countryCode: "ET",
    country: "Ethiopia",
    flag: "🇪🇹",
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    decimals: 2,
    countryCode: "EU",
    country: "European Union",
    flag: "🇪🇺",
    popular: true,
    aliases: ["Austria","Belgium","Bulgaria","Croatia","Cyprus","Estonia","Finland","France","Germany","Greece","Ireland","Italy","Latvia","Lithuania","Luxembourg","Malta","Netherlands","Portugal","Slovakia","Slovenia","Spain","Eurozone"],
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "FJD",
    decimals: 2,
    countryCode: "FJ",
    country: "Fiji",
    flag: "🇫🇯",
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    symbol: "FKP",
    decimals: 2,
    countryCode: "FK",
    country: "Falkland Islands",
    flag: "🇫🇰",
  },
  {
    code: "FOK",
    name: "FOK",
    symbol: "FOK",
    decimals: 2,
    countryCode: "FO",
    country: "Faroe Islands",
    flag: "🇫🇴",
  },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    decimals: 2,
    countryCode: "GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    popular: true,
    aliases: ["Isle of Man","Jersey","Guernsey","England","Scotland","Wales","Northern Ireland"],
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    decimals: 2,
    countryCode: "GE",
    country: "Georgia",
    flag: "🇬🇪",
  },
  {
    code: "GGP",
    name: "GGP",
    symbol: "GGP",
    decimals: 2,
    countryCode: "GG",
    country: "Guernsey",
    flag: "🇬🇬",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "₵",
    decimals: 2,
    countryCode: "GH",
    country: "Ghana",
    flag: "🇬🇭",
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    symbol: "GIP",
    decimals: 2,
    countryCode: "GI",
    country: "Gibraltar",
    flag: "🇬🇮",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    symbol: "GMD",
    decimals: 2,
    countryCode: "GM",
    country: "Gambia",
    flag: "🇬🇲",
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    symbol: "GNF",
    decimals: 0,
    countryCode: "GN",
    country: "Guinea",
    flag: "🇬🇳",
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "GTQ",
    decimals: 2,
    countryCode: "GT",
    country: "Guatemala",
    flag: "🇬🇹",
  },
  {
    code: "GYD",
    name: "Guyanaese Dollar",
    symbol: "GYD",
    decimals: 2,
    countryCode: "GY",
    country: "Guyana",
    flag: "🇬🇾",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    decimals: 2,
    countryCode: "HK",
    country: "Hong Kong",
    flag: "🇭🇰",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    symbol: "HNL",
    decimals: 2,
    countryCode: "HN",
    country: "Honduras",
    flag: "🇭🇳",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    symbol: "HTG",
    decimals: 2,
    countryCode: "HT",
    country: "Haiti",
    flag: "🇭🇹",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    decimals: 2,
    countryCode: "HU",
    country: "Hungary",
    flag: "🇭🇺",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    decimals: 0,
    countryCode: "ID",
    country: "Indonesia",
    flag: "🇮🇩",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    symbol: "₪",
    decimals: 2,
    countryCode: "IL",
    country: "Israel",
    flag: "🇮🇱",
    aliases: ["Palestine","Gaza"],
  },
  {
    code: "IMP",
    name: "IMP",
    symbol: "IMP",
    decimals: 2,
    countryCode: "IM",
    country: "Isle of Man",
    flag: "🇮🇲",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    decimals: 2,
    countryCode: "IN",
    country: "India",
    flag: "🇮🇳",
    popular: true,
    aliases: ["Bhutan"],
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "IQD",
    decimals: 0,
    countryCode: "IQ",
    country: "Iraq",
    flag: "🇮🇶",
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    symbol: "IRR",
    decimals: 0,
    countryCode: "IR",
    country: "Iran",
    flag: "🇮🇷",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    decimals: 0,
    countryCode: "IS",
    country: "Iceland",
    flag: "🇮🇸",
  },
  {
    code: "JEP",
    name: "JEP",
    symbol: "JEP",
    decimals: 2,
    countryCode: "JE",
    country: "Jersey",
    flag: "🇯🇪",
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "JMD",
    decimals: 2,
    countryCode: "JM",
    country: "Jamaica",
    flag: "🇯🇲",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "د.ا",
    decimals: 3,
    countryCode: "JO",
    country: "Jordan",
    flag: "🇯🇴",
    aliases: ["Palestine","West Bank"],
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    decimals: 0,
    countryCode: "JP",
    country: "Japan",
    flag: "🇯🇵",
    popular: true,
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    decimals: 2,
    countryCode: "KE",
    country: "Kenya",
    flag: "🇰🇪",
  },
  {
    code: "KGS",
    name: "Kyrgystani Som",
    symbol: "KGS",
    decimals: 2,
    countryCode: "KG",
    country: "Kyrgyzstan",
    flag: "🇰🇬",
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    symbol: "KHR",
    decimals: 2,
    countryCode: "KH",
    country: "Cambodia",
    flag: "🇰🇭",
  },
  {
    code: "KID",
    name: "KID",
    symbol: "KID",
    decimals: 2,
    countryCode: "KI",
    country: "Kiribati",
    flag: "🇰🇮",
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    symbol: "KMF",
    decimals: 0,
    countryCode: "KM",
    country: "Comoros",
    flag: "🇰🇲",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    decimals: 0,
    countryCode: "KR",
    country: "South Korea",
    flag: "🇰🇷",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "د.ك",
    decimals: 3,
    countryCode: "KW",
    country: "Kuwait",
    flag: "🇰🇼",
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    symbol: "KYD",
    decimals: 2,
    countryCode: "KY",
    country: "Cayman Islands",
    flag: "🇰🇾",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    decimals: 2,
    countryCode: "KZ",
    country: "Kazakhstan",
    flag: "🇰🇿",
  },
  {
    code: "LAK",
    name: "Laotian Kip",
    symbol: "LAK",
    decimals: 0,
    countryCode: "LA",
    country: "Laos",
    flag: "🇱🇦",
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "ل.ل",
    decimals: 2,
    countryCode: "LB",
    country: "Lebanon",
    flag: "🇱🇧",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    decimals: 2,
    countryCode: "LK",
    country: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    symbol: "LRD",
    decimals: 2,
    countryCode: "LR",
    country: "Liberia",
    flag: "🇱🇷",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    symbol: "LSL",
    decimals: 2,
    countryCode: "LS",
    country: "Lesotho",
    flag: "🇱🇸",
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    symbol: "LYD",
    decimals: 3,
    countryCode: "LY",
    country: "Libya",
    flag: "🇱🇾",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "د.م.",
    decimals: 2,
    countryCode: "MA",
    country: "Morocco",
    flag: "🇲🇦",
    aliases: ["Western Sahara"],
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    symbol: "MDL",
    decimals: 2,
    countryCode: "MD",
    country: "Moldova",
    flag: "🇲🇩",
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    symbol: "MGA",
    decimals: 0,
    countryCode: "MG",
    country: "Madagascar",
    flag: "🇲🇬",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "MKD",
    decimals: 2,
    countryCode: "MK",
    country: "North Macedonia",
    flag: "🇲🇰",
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    symbol: "MMK",
    decimals: 0,
    countryCode: "MM",
    country: "Myanmar (Burma)",
    flag: "🇲🇲",
  },
  {
    code: "MNT",
    name: "Mongolian Tugrik",
    symbol: "MNT",
    decimals: 2,
    countryCode: "MN",
    country: "Mongolia",
    flag: "🇲🇳",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    symbol: "MOP",
    decimals: 2,
    countryCode: "MO",
    country: "Macao SAR China",
    flag: "🇲🇴",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    symbol: "MRU",
    decimals: 2,
    countryCode: "MR",
    country: "Mauritania",
    flag: "🇲🇷",
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    symbol: "MUR",
    decimals: 2,
    countryCode: "MU",
    country: "Mauritius",
    flag: "🇲🇺",
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    symbol: "MVR",
    decimals: 2,
    countryCode: "MV",
    country: "Maldives",
    flag: "🇲🇻",
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    symbol: "MWK",
    decimals: 2,
    countryCode: "MW",
    country: "Malawi",
    flag: "🇲🇼",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    decimals: 2,
    countryCode: "MX",
    country: "Mexico",
    flag: "🇲🇽",
    popular: true,
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    decimals: 2,
    countryCode: "MY",
    country: "Malaysia",
    flag: "🇲🇾",
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MZN",
    decimals: 2,
    countryCode: "MZ",
    country: "Mozambique",
    flag: "🇲🇿",
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    symbol: "NAD",
    decimals: 2,
    countryCode: "NA",
    country: "Namibia",
    flag: "🇳🇦",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    decimals: 2,
    countryCode: "NG",
    country: "Nigeria",
    flag: "🇳🇬",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    symbol: "NIO",
    decimals: 2,
    countryCode: "NI",
    country: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    decimals: 2,
    countryCode: "NO",
    country: "Norway",
    flag: "🇳🇴",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "रू",
    decimals: 2,
    countryCode: "NP",
    country: "Nepal",
    flag: "🇳🇵",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "$",
    decimals: 2,
    countryCode: "NZ",
    country: "New Zealand",
    flag: "🇳🇿",
    popular: true,
    aliases: ["Cook Islands","Niue","Tokelau"],
  },
  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "ر.ع.",
    decimals: 3,
    countryCode: "OM",
    country: "Oman",
    flag: "🇴🇲",
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    symbol: "PAB",
    decimals: 2,
    countryCode: "PA",
    country: "Panama",
    flag: "🇵🇦",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    decimals: 2,
    countryCode: "PE",
    country: "Peru",
    flag: "🇵🇪",
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "PGK",
    decimals: 2,
    countryCode: "PG",
    country: "Papua New Guinea",
    flag: "🇵🇬",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    decimals: 2,
    countryCode: "PH",
    country: "Philippines",
    flag: "🇵🇭",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    decimals: 2,
    countryCode: "PK",
    country: "Pakistan",
    flag: "🇵🇰",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    decimals: 2,
    countryCode: "PL",
    country: "Poland",
    flag: "🇵🇱",
  },
  {
    code: "PYG",
    name: "Paraguayan Guarani",
    symbol: "PYG",
    decimals: 0,
    countryCode: "PY",
    country: "Paraguay",
    flag: "🇵🇾",
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    symbol: "ر.ق",
    decimals: 2,
    countryCode: "QA",
    country: "Qatar",
    flag: "🇶🇦",
  },
  {
    code: "RON",
    name: "Romanian Leu",
    symbol: "lei",
    decimals: 2,
    countryCode: "RO",
    country: "Romania",
    flag: "🇷🇴",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    symbol: "дин.",
    decimals: 2,
    countryCode: "RS",
    country: "Serbia",
    flag: "🇷🇸",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "RUB",
    decimals: 2,
    countryCode: "RU",
    country: "Russia",
    flag: "🇷🇺",
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    symbol: "RWF",
    decimals: 0,
    countryCode: "RW",
    country: "Rwanda",
    flag: "🇷🇼",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    decimals: 2,
    countryCode: "SA",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "SBD",
    decimals: 2,
    countryCode: "SB",
    country: "Solomon Islands",
    flag: "🇸🇧",
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    symbol: "SCR",
    decimals: 2,
    countryCode: "SC",
    country: "Seychelles",
    flag: "🇸🇨",
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    symbol: "SDG",
    decimals: 2,
    countryCode: "SD",
    country: "Sudan",
    flag: "🇸🇩",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    decimals: 2,
    countryCode: "SE",
    country: "Sweden",
    flag: "🇸🇪",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    decimals: 2,
    countryCode: "SG",
    country: "Singapore",
    flag: "🇸🇬",
    popular: true,
    aliases: ["Brunei"],
  },
  {
    code: "SHP",
    name: "St. Helena Pound",
    symbol: "SHP",
    decimals: 2,
    countryCode: "SH",
    country: "St. Helena",
    flag: "🇸🇭",
  },
  {
    code: "SLE",
    name: "Sierra Leonean Leone",
    symbol: "SLE",
    decimals: 2,
    countryCode: "SL",
    country: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    symbol: "SOS",
    decimals: 0,
    countryCode: "SO",
    country: "Somalia",
    flag: "🇸🇴",
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    symbol: "SRD",
    decimals: 2,
    countryCode: "SR",
    country: "Suriname",
    flag: "🇸🇷",
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    symbol: "SSP",
    decimals: 2,
    countryCode: "SS",
    country: "South Sudan",
    flag: "🇸🇸",
  },
  {
    code: "STN",
    name: "São Tomé & Príncipe Dobra",
    symbol: "STN",
    decimals: 2,
    countryCode: "ST",
    country: "São Tomé & Príncipe",
    flag: "🇸🇹",
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    symbol: "SYP",
    decimals: 0,
    countryCode: "SY",
    country: "Syria",
    flag: "🇸🇾",
  },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    symbol: "SZL",
    decimals: 2,
    countryCode: "SZ",
    country: "Eswatini",
    flag: "🇸🇿",
  },
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    decimals: 2,
    countryCode: "TH",
    country: "Thailand",
    flag: "🇹🇭",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "TJS",
    decimals: 2,
    countryCode: "TJ",
    country: "Tajikistan",
    flag: "🇹🇯",
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    symbol: "TMT",
    decimals: 2,
    countryCode: "TM",
    country: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: "د.ت",
    decimals: 3,
    countryCode: "TN",
    country: "Tunisia",
    flag: "🇹🇳",
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    symbol: "TOP",
    decimals: 2,
    countryCode: "TO",
    country: "Tonga",
    flag: "🇹🇴",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    decimals: 2,
    countryCode: "TR",
    country: "Türkiye",
    flag: "🇹🇷",
    aliases: ["Northern Cyprus"],
  },
  {
    code: "TTD",
    name: "Trinidad & Tobago Dollar",
    symbol: "TTD",
    decimals: 2,
    countryCode: "TT",
    country: "Trinidad & Tobago",
    flag: "🇹🇹",
  },
  {
    code: "TVD",
    name: "TVD",
    symbol: "TVD",
    decimals: 2,
    countryCode: "TV",
    country: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    decimals: 2,
    countryCode: "TW",
    country: "Taiwan",
    flag: "🇹🇼",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
    decimals: 2,
    countryCode: "TZ",
    country: "Tanzania",
    flag: "🇹🇿",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    decimals: 2,
    countryCode: "UA",
    country: "Ukraine",
    flag: "🇺🇦",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    decimals: 0,
    countryCode: "UG",
    country: "Uganda",
    flag: "🇺🇬",
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    decimals: 2,
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    popular: true,
    aliases: ["Ecuador","El Salvador","Panama","Timor-Leste","Zimbabwe","Puerto Rico"],
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    symbol: "$U",
    decimals: 2,
    countryCode: "UY",
    country: "Uruguay",
    flag: "🇺🇾",
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "UZS",
    decimals: 2,
    countryCode: "UZ",
    country: "Uzbekistan",
    flag: "🇺🇿",
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    symbol: "VES",
    decimals: 2,
    countryCode: "VE",
    country: "Venezuela",
    flag: "🇻🇪",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    decimals: 0,
    countryCode: "VN",
    country: "Vietnam",
    flag: "🇻🇳",
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    symbol: "VUV",
    decimals: 0,
    countryCode: "VU",
    country: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    code: "WST",
    name: "Samoan Tala",
    symbol: "WST",
    decimals: 2,
    countryCode: "WS",
    country: "Samoa",
    flag: "🇼🇸",
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    decimals: 0,
    countryCode: "CM",
    country: "Central African CFA zone",
    flag: "🇨🇲",
    aliases: ["Cameroon","Central African Republic","Chad","Congo","Equatorial Guinea","Gabon"],
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "EC$",
    decimals: 2,
    countryCode: "AG",
    country: "Eastern Caribbean",
    flag: "🇦🇬",
    aliases: ["Antigua and Barbuda","Dominica","Grenada","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Anguilla","Montserrat"],
  },
  {
    code: "XCG",
    name: "Caribbean guilder",
    symbol: "Cg.",
    decimals: 2,
    countryCode: "CW",
    country: "Curaçao & Sint Maarten",
    flag: "🇨🇼",
    aliases: ["Curaçao","Sint Maarten"],
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "F CFA",
    decimals: 0,
    countryCode: "SN",
    country: "West African CFA zone",
    flag: "🇸🇳",
    aliases: ["Benin","Burkina Faso","Côte d'Ivoire","Ivory Coast","Guinea-Bissau","Mali","Niger","Senegal","Togo"],
  },
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: "CFPF",
    decimals: 0,
    countryCode: "PF",
    country: "French Pacific",
    flag: "🇵🇫",
    aliases: ["French Polynesia","New Caledonia","Wallis and Futuna","Tahiti"],
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    symbol: "YER",
    decimals: 0,
    countryCode: "YE",
    country: "Yemen",
    flag: "🇾🇪",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    decimals: 2,
    countryCode: "ZA",
    country: "South Africa",
    flag: "🇿🇦",
    popular: true,
    aliases: ["Lesotho","Namibia","Eswatini"],
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    symbol: "ZMW",
    decimals: 2,
    countryCode: "ZM",
    country: "Zambia",
    flag: "🇿🇲",
  },
  {
    code: "ZWG",
    name: "Zimbabwean Gold",
    symbol: "ZWG",
    decimals: 2,
    countryCode: "ZW",
    country: "Zimbabwe",
    flag: "🇿🇼",
  },
];

export const CURRENCIES: readonly Currency[] = DATA;

export const CURRENCY_BY_CODE: ReadonlyMap<string, Currency> = new Map(
  DATA.map((currency) => [currency.code, currency]),
);

export function getCurrency(code: string): Currency | undefined {
  return CURRENCY_BY_CODE.get(code.toUpperCase());
}

export const POPULAR_CODES: readonly string[] = DATA.filter(
  (currency) => currency.popular,
).map((currency) => currency.code);
